version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true
    excludes: [] # put task names in here which are overwritten in this file
    vars:
      NESTED_MODULES: api
      API_DIRS: '{{.ROOT_DIR}}/api/provider/v1alpha1/... {{.ROOT_DIR}}/api/clusters/v1alpha1/...'
      MANIFEST_OUT: '{{.ROOT_DIR}}/api/crds/manifests'
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/test/... {{.ROOT_DIR}}/api/provider/v1alpha1/... {{.ROOT_DIR}}/api/clusters/v1alpha1/...'
      COMPONENTS: 'openmcp-operator'
      REPO_URL: 'https://github.com/openmcp-project/openmcp-operator'
      GENERATE_DOCS_INDEX: "true"
      CHART_COMPONENTS: "[]"
      LINTER_VERSION: "v1.64.4"
