//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v2alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"

	"github.com/openmcp-project/openmcp-operator/api/common"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMConfig) DeepCopyInto(out *IAMConfig) {
	*out = *in
	if in.RoleBindings != nil {
		in, out := &in.RoleBindings, &out.RoleBindings
		*out = make([]common.RoleBindings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OIDCProviders != nil {
		in, out := &in.OIDCProviders, &out.OIDCProviders
		*out = make([]*common.OIDCProviderConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(common.OIDCProviderConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMConfig.
func (in *IAMConfig) DeepCopy() *IAMConfig {
	if in == nil {
		return nil
	}
	out := new(IAMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedControlPlaneV2) DeepCopyInto(out *ManagedControlPlaneV2) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedControlPlaneV2.
func (in *ManagedControlPlaneV2) DeepCopy() *ManagedControlPlaneV2 {
	if in == nil {
		return nil
	}
	out := new(ManagedControlPlaneV2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedControlPlaneV2) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedControlPlaneV2List) DeepCopyInto(out *ManagedControlPlaneV2List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedControlPlaneV2, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedControlPlaneV2List.
func (in *ManagedControlPlaneV2List) DeepCopy() *ManagedControlPlaneV2List {
	if in == nil {
		return nil
	}
	out := new(ManagedControlPlaneV2List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedControlPlaneV2List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedControlPlaneV2Spec) DeepCopyInto(out *ManagedControlPlaneV2Spec) {
	*out = *in
	in.IAM.DeepCopyInto(&out.IAM)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedControlPlaneV2Spec.
func (in *ManagedControlPlaneV2Spec) DeepCopy() *ManagedControlPlaneV2Spec {
	if in == nil {
		return nil
	}
	out := new(ManagedControlPlaneV2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedControlPlaneV2Status) DeepCopyInto(out *ManagedControlPlaneV2Status) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = make(map[string]common.LocalObjectReference, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedControlPlaneV2Status.
func (in *ManagedControlPlaneV2Status) DeepCopy() *ManagedControlPlaneV2Status {
	if in == nil {
		return nil
	}
	out := new(ManagedControlPlaneV2Status)
	in.DeepCopyInto(out)
	return out
}
