//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1 "github.com/fluxcd/source-controller/api/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"

	clustersv1alpha1 "github.com/openmcp-project/openmcp-operator/api/clusters/v1alpha1"
	"github.com/openmcp-project/openmcp-operator/api/common"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartSource) DeepCopyInto(out *ChartSource) {
	*out = *in
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(apiv1.HelmRepositorySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(apiv1.GitRepositorySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(apiv1.OCIRepositorySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartSource.
func (in *ChartSource) DeepCopy() *ChartSource {
	if in == nil {
		return nil
	}
	out := new(ChartSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmDeployerConfig) DeepCopyInto(out *HelmDeployerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmDeployerConfig.
func (in *HelmDeployerConfig) DeepCopy() *HelmDeployerConfig {
	if in == nil {
		return nil
	}
	out := new(HelmDeployerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmDeployerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmDeployerConfigList) DeepCopyInto(out *HelmDeployerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HelmDeployerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmDeployerConfigList.
func (in *HelmDeployerConfigList) DeepCopy() *HelmDeployerConfigList {
	if in == nil {
		return nil
	}
	out := new(HelmDeployerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmDeployerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmDeployerConfigSpec) DeepCopyInto(out *HelmDeployerConfigSpec) {
	*out = *in
	in.HelmReleaseReconciliationIntervals.DeepCopyInto(&out.HelmReleaseReconciliationIntervals)
	if in.SelectorDefinitions != nil {
		in, out := &in.SelectorDefinitions, &out.SelectorDefinitions
		*out = make(map[string]SelectorDefinition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmDeployerConfigSpec.
func (in *HelmDeployerConfigSpec) DeepCopy() *HelmDeployerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(HelmDeployerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmDeployment) DeepCopyInto(out *HelmDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmDeployment.
func (in *HelmDeployment) DeepCopy() *HelmDeployment {
	if in == nil {
		return nil
	}
	out := new(HelmDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmDeploymentList) DeepCopyInto(out *HelmDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HelmDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmDeploymentList.
func (in *HelmDeploymentList) DeepCopy() *HelmDeploymentList {
	if in == nil {
		return nil
	}
	out := new(HelmDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmDeploymentSpec) DeepCopyInto(out *HelmDeploymentSpec) {
	*out = *in
	in.ChartSource.DeepCopyInto(&out.ChartSource)
	if in.SelectorName != nil {
		in, out := &in.SelectorName, &out.SelectorName
		*out = new(string)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(clustersv1alpha1.IdentityLabelPurposeSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.HelmValues != nil {
		in, out := &in.HelmValues, &out.HelmValues
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmDeploymentSpec.
func (in *HelmDeploymentSpec) DeepCopy() *HelmDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(HelmDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmDeploymentStatus) DeepCopyInto(out *HelmDeploymentStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmDeploymentStatus.
func (in *HelmDeploymentStatus) DeepCopy() *HelmDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(HelmDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseReconciliationIntervalConfig) DeepCopyInto(out *HelmReleaseReconciliationIntervalConfig) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(v1.Duration)
		**out = **in
	}
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseReconciliationIntervalConfig.
func (in *HelmReleaseReconciliationIntervalConfig) DeepCopy() *HelmReleaseReconciliationIntervalConfig {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseReconciliationIntervalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopy) DeepCopyInto(out *SecretCopy) {
	*out = *in
	out.Source = in.Source
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(common.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopy.
func (in *SecretCopy) DeepCopy() *SecretCopy {
	if in == nil {
		return nil
	}
	out := new(SecretCopy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsToCopy) DeepCopyInto(out *SecretsToCopy) {
	*out = *in
	if in.ToPlatformCluster != nil {
		in, out := &in.ToPlatformCluster, &out.ToPlatformCluster
		*out = make([]SecretCopy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ToTargetCluster != nil {
		in, out := &in.ToTargetCluster, &out.ToTargetCluster
		*out = make([]SecretCopy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsToCopy.
func (in *SecretsToCopy) DeepCopy() *SecretsToCopy {
	if in == nil {
		return nil
	}
	out := new(SecretsToCopy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectorDefinition) DeepCopyInto(out *SelectorDefinition) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(clustersv1alpha1.IdentityLabelPurposeSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretsToCopy != nil {
		in, out := &in.SecretsToCopy, &out.SecretsToCopy
		*out = new(SecretsToCopy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectorDefinition.
func (in *SelectorDefinition) DeepCopy() *SelectorDefinition {
	if in == nil {
		return nil
	}
	out := new(SelectorDefinition)
	in.DeepCopyInto(out)
	return out
}
